"""
Builds systems.json (every indexed system, merged into one file) plus one
systems/<slug>.json per system, and design-system.schema.json documenting
the shape — the "both formats per record" and "receipts" patterns from
https://state-of-ai-in-design-systems.netlify.app/ai's own AI-facing exports:
markdown/HTML to read, JSON to count with, re-fetch, or diff against a
previous run. Until now this directory only ever published HTML — an agent
wanting "every system's resources and signals" had to scrape ~250 pages to
get data that already exists as plain Python dicts at build time.

Archived (graveyard) entries are deliberately excluded, same as every other
public-facing page (generate_directory.py's indexed_only()) — this is the
same "systems you can actually search today" set, just as JSON instead of HTML.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from generate_directory import coverage_status, indexed_only, load_pages_index, load_systems
from slug import slugify
from text_utils import full_name, split_org_name

SYSTEMS_JSON_FILE = Path(__file__).parent / "systems.json"
SCHEMA_FILE = Path(__file__).parent / "design-system.schema.json"
SYSTEMS_JSON_DIR = Path(__file__).parent / "systems"


def build_record(entry: dict, pages_index: dict) -> dict:
    org, ds_name = split_org_name(entry)
    name = full_name(entry)
    slug = slugify(name)
    pages = pages_index.get(name) or []
    return {
        "id": slug,
        "organization": org or None,
        "design_system": ds_name,
        "full_name": name,
        "start_urls": entry.get("start_urls") or [],
        "detail_url": f"/systems/{slug}",
        "pages_indexed": entry.get("pages_indexed"),
        "coverage_status": coverage_status(entry),
        "hit_max_pages": bool(entry.get("hit_max_pages")),
        "likely_spa": bool(entry.get("likely_spa")),
        "last_checked": entry.get("last_checked"),
        "last_modified": entry.get("last_modified") or None,
        "sitemap_last_modified": entry.get("sitemap_last_modified") or None,
        "resources": entry.get("resources") or {},
        "unverified_resources": entry.get("unverified_resources") or {},
        "content_signals": entry.get("content_signals") or {},
        "github_meta": entry.get("github_meta") or None,
        "npm_meta": entry.get("npm_meta") or None,
        "indexed_pages": [{"url": p["url"], "title": p["title"]} for p in pages],
    }


def build_export(entries: list[dict], pages_index: dict) -> dict:
    records = [build_record(e, pages_index) for e in entries]
    checked_dates = [r["last_checked"] for r in records if r.get("last_checked")]
    return {
        "$schema": "./design-system.schema.json",
        # Same "staleness note" pattern as llms.txt (see generate_llms_txt.py)
        # — this is a live, rolling-refresh dataset, not a fixed snapshot, so
        # both dates matter: when THIS FILE was written, and the oldest a
        # record in it could be (the least-recently-checked system).
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "data_as_of": min(checked_dates) if checked_dates else None,
        "total_systems": len(records),
        "systems": records,
    }


SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ds-directory-mcp/design-system.schema.json",
    "title": "Design Systems Directory export",
    "description": (
        "Shape of systems.json (every indexed system) and each systems/<slug>.json "
        "(one system, same record). Archived/dead systems are excluded — see "
        "systems.yaml's own 'archived' field if you need those too. Generated by "
        "generate_data_export.py; never hand-edited."
    ),
    "type": "object",
    "properties": {
        "generated_at": {"type": "string", "format": "date-time", "description": "When this file was built."},
        "data_as_of": {
            "type": ["string", "null"],
            "format": "date-time",
            "description": "The OLDEST last_checked among all included records — the honest staleness bound for the whole file, not just when it was generated.",
        },
        "total_systems": {"type": "integer"},
        "systems": {"type": "array", "items": {"$ref": "#/$defs/system"}},
    },
    "required": ["generated_at", "total_systems", "systems"],
    "$defs": {
        "system": {
            "type": "object",
            "properties": {
                "id": {"type": "string", "description": "URL slug — also the systems/<id>.json / systems/<id>.html filename."},
                "organization": {"type": ["string", "null"]},
                "design_system": {"type": "string"},
                "full_name": {"type": "string", "description": "\"Organization — Design system\", or just the name when they're the same."},
                "start_urls": {"type": "array", "items": {"type": "string", "format": "uri"}},
                "detail_url": {"type": "string", "description": "Root-relative path to this system's own HTML page."},
                "pages_indexed": {"type": ["integer", "null"]},
                "coverage_status": {"enum": ["full", "partial", "unknown"]},
                "hit_max_pages": {"type": "boolean", "description": "True if the crawl stopped at its page cap with more real content still queued."},
                "likely_spa": {"type": "boolean", "description": "True if the crawler found no usable static HTML (a JS-rendered site it can't see through)."},
                "last_checked": {"type": ["string", "null"], "format": "date-time"},
                "last_modified": {"type": ["string", "null"], "description": "The start URL's own Last-Modified header, if the server sent one."},
                "sitemap_last_modified": {"type": ["string", "null"], "description": "Max <lastmod> across the site's sitemap, if it has one — a stronger freshness signal than last_modified alone."},
                "resources": {
                    "type": "object",
                    "description": "Discovered links by category (github, npm, storybook, figma, mcp, skills, agent_instructions, copilot_instructions, cursor_rules, registry, icons, markdown_docs) — each value is a list of URLs, since a system can have more than one of the same type.",
                    "additionalProperties": {"type": "array", "items": {"type": "string", "format": "uri"}},
                },
                "unverified_resources": {
                    "type": "object",
                    "description": "Subset of resources.github/npm whose name doesn't obviously relate to this system (see resources.py's looks_related()) — flagged for a human to double-check, not necessarily wrong.",
                },
                "content_signals": {
                    "type": "object",
                    "description": "Best-effort signals detected from crawled page text — see content_signals.py.",
                    "properties": {
                        "accessibility_conformance": {"type": "string"},
                        "tokens_format": {"type": "string"},
                        "frameworks": {"type": "array", "items": {"type": "string"}},
                        "dark_mode": {"type": "boolean"},
                        "multi_brand": {"type": "boolean"},
                        "governance_model": {"type": "boolean"},
                        "deprecation_policy": {"type": "boolean"},
                        "cli_scaffolding": {"type": "boolean"},
                        "codemods": {"type": "boolean"},
                        "figma_code_connect": {"type": "boolean"},
                        "prompt_library": {"type": "boolean"},
                    },
                },
                "github_meta": {
                    "type": ["object", "null"],
                    "properties": {
                        "license": {"type": ["string", "null"]},
                        "stars": {"type": ["integer", "null"]},
                        "last_pushed": {"type": ["string", "null"]},
                    },
                },
                "npm_meta": {
                    "type": ["object", "null"],
                    "properties": {
                        "latest_version": {"type": ["string", "null"]},
                        "weekly_downloads": {"type": ["integer", "null"]},
                    },
                },
                "indexed_pages": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {"url": {"type": "string", "format": "uri"}, "title": {"type": "string"}},
                        "required": ["url", "title"],
                    },
                },
            },
            "required": ["id", "design_system", "full_name", "start_urls", "detail_url"],
        }
    },
}


def main() -> None:
    entries = indexed_only(load_systems())
    pages_index = load_pages_index()
    export = build_export(entries, pages_index)

    SYSTEMS_JSON_FILE.write_text(json.dumps(export, indent=2, ensure_ascii=False))
    SCHEMA_FILE.write_text(json.dumps(SCHEMA, indent=2, ensure_ascii=False))

    SYSTEMS_JSON_DIR.mkdir(exist_ok=True)
    wanted_ids = {record["id"] for record in export["systems"]}
    # See generate_systems.py's main() for why: a system no longer in
    # indexed_only()'s output otherwise leaves its old <slug>.json behind
    # forever, still deployed.
    for existing in SYSTEMS_JSON_DIR.glob("*.json"):
        if existing.stem not in wanted_ids:
            existing.unlink()
    for record in export["systems"]:
        per_system = {
            "$schema": "../design-system.schema.json#/$defs/system",
            "generated_at": export["generated_at"],
            **record,
        }
        (SYSTEMS_JSON_DIR / f"{record['id']}.json").write_text(
            json.dumps(per_system, indent=2, ensure_ascii=False)
        )

    print(f"Wrote {SYSTEMS_JSON_FILE}, {SCHEMA_FILE}, and {len(export['systems'])} systems/<slug>.json files.")


if __name__ == "__main__":
    main()
